# Generated by Django 4.0.1 on 2022-01-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura_simple',
            name='destino',
        ),
        migrations.AlterField(
            model_name='factura_simple',
            name='origen',
            field=models.TextField(max_length=1000),
        ),
    ]
