# Generated by Django 4.0.1 on 2022-01-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cp',
            field=models.CharField(default='41520', max_length=50),
        ),
    ]
