# Generated by Django 4.0.1 on 2022-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0002_empresa_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='localidad',
            field=models.CharField(default='EL VISO DEL ALCOR', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(default='Sevilla', max_length=50),
        ),
    ]
