# Generated by Django 4.0.1 on 2022-01-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0002_remove_factura_simple_destino_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura_simple',
            old_name='origen',
            new_name='concepto',
        ),
    ]
