# Generated by Django 4.0.1 on 2022-01-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0003_empresa_localidad_empresa_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
