# Generated by Django 4.0.1 on 2022-01-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0003_rename_origen_factura_simple_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='factura',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
