# Generated by Django 4.0.1 on 2022-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0005_factura_simple_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=50)),
                ('cif', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=50)),
                ('iva', models.CharField(max_length=50)),
                ('lavado', models.CharField(max_length=50)),
                ('retencion', models.CharField(max_length=50)),
                ('kilosminimos', models.CharField(max_length=50)),
            ],
        ),
    ]
