# Generated by Django 4.0.1 on 2022-01-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0007_empresa_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='imagen',
        ),
    ]
