# Generated by Django 4.0.1 on 2022-01-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0008_remove_empresa_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cif',
        ),
    ]
