# Generated by Django 4.0.1 on 2022-01-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0009_remove_factura_cif'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cif',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='Factura.cliente'),
        ),
    ]
